### ISSUE TITLE
Flutter app: unofficial vendor builds should have a distinct skin

### ISSUE THREAD

**Issue by relja128** [mlcommons/mobile_app_open#175]
Allow vendors to build an unofficial version that would have a clearly different skin (brown instead of blue, "Results" -> "Unverified results").

Presence of a config file (uverified.version - can be 0 bytes) should be the key that enables this mode.

Will discuss more in the eng meeting.

**Comment by anhappdev** [comment]
I use environment variable instead of an empty file because it should be easier to integrate with CI system.
By default, the app will be built with the unofficial UI because it's the most common and to avoid accidentally using the official UI.

This is how the UI looks:

![IMG_7272 Medium](https://user-images.githubusercontent.com/85728587/148040295-4194816b-1153-469e-a3a4-76578c2c027b.jpeg) ![IMG_7275 Medium](https://user-images.githubusercontent.com/85728587/148040306-e55bb246-342b-40a8-930e-a614f4e26295.jpeg)

![IMG_7273 Medium](https://user-images.githubusercontent.com/85728587/148040542-0947812e-6357-40fb-8f1b-ff5b9908b087.jpeg) ![IMG_7274 Medium](https://user-images.githubusercontent.com/85728587/148040566-08fd5aba-4199-48b2-9f60-19a24dfab096.jpeg)
