### ISSUE TITLE
md5 check requires the model to be a single file [Flutter]

### ISSUE THREAD

**Issue by mkankana** [mlcommons/mobile_app_open#346]
1. Intel models representation consists of 2 files, however the md5 check only lets me add 1 file
2. If I set this to the MD5 of the zip file then the unziped model files can be replaced easily .
3. Please suggest a way to handle multiple model files

**Comment by d-uzlov** [comment]
I believe that our md5 checksum validation is intended to catch internet issues. Particularly it's possible to download a stub file from Git LFS instead of the original file if we reach download limit.

Checksum validation was not meant to prevent users from messing with application files.
Even though currently the app validates checksums for single-file models, it only does this on startup, and there is nothing preventing users from changing files after the validation.

**Comment by anhappdev** [comment]
MD5 check was intended to check for file corruption when they are first downloaded from the internet.
@mkankana If you need checksum validation against file manipulation, please request it in the mobile engineering meeting.

**Comment by mkankana** [comment]
Makes sense. So this is only checked once in the beginning or if user clears the cached files. Is my understanding correct ?

**Comment by anhappdev** [comment]
The app runs the check every time the files are downloaded, at the beginning and also when the cache is cleared because it will re-download the files again.

**Comment by mkankana** [comment]
I'll make this the MD5 for zip file in that case. 
This issue can be closed
