### ISSUE TITLE
Please share some instructions to create a release build on windows (Flutter)

### ISSUE THREAD

**Issue by mkankana** [mlcommons/mobile_app_open#353]
Since our source code is internal and not published on this repo , could someone share instructions of how to generate a release build on windows (flutter). So that we can test for performance.

**Comment by d-uzlov** [comment]
Benchmarks are run by the native code which is built in release mode by default. Even if you see "Debug" label in UI this shouldn't affect performance because only UI is built in debug mode.

You can get rid of "Debug" label by running `flutter build windows` in the `flutter` directory of the repo, and then running the app from `flutter/build/windows/runner/Release/mobile_app_flutter2.exe`.
For a real release you would also need to copy some `.dll` files which are distributed with Visual Studio but are not usually present on machines without MSVS.
But all of this will not change performance.

**Comment by freedomtan** [comment]
Since performance doesn't change between debug and release modes, we don't really need this. Close this for now.
