### ISSUE TITLE
Implementing a new backend for benchmark

### ISSUE THREAD

**Issue by NullCarrier** [mlcommons/mobile_app_open#369]
Hi，I am trying to implement a new backend for RK (Rockchip) based on rk3588. I have a few questions about testing this benchmark via the command line tool (the main binary file). 

1. For testing accuracy by imageNet dataset for mobile_edge_tpu, I can't find the mean and std for this model anywhere in this repo and other repo as well. Can anyone tell me what should be the mean and std for this model **as well as for other models** that require for mobile inference 2.0? 
2. Where I can find the label for imageNet dataset? I can't reproduce the same accuracy result even with the tflite backend for mobilenet_edge_tpu. Can anyone upload the imagenet_val_full.txt for groundtruth file?
3. For every task in the benchmark, should vendor only provide one model for each task for submission?

Thanks,

**Comment by freedomtan** [comment]
> Hi，I am trying to implement a new backend for RK (Rockchip) based on rk3588. I have a few questions about testing this benchmark via the command line tool (the main binary file).
> 

Great to hear that.

> 1. For testing accuracy by imageNet dataset for mobile_edge_tpu, I can't find the mean and std for this model anywhere in this repo and other repo as well. Can anyone tell me what should be the mean and std for this model **as well as for other models** that require for mobile inference 2.0?

For mean and std, I assume you mean values used in normalization of inputs. For MobileNet EdgeTPU, or to be more precise, for ImageNet, the normalization is done at https://github.com/mlcommons/mobile_app_open/blob/master/flutter/cpp/datasets/imagenet.cc#L85
```C++
  builder.AddDefaultNormalizationStep();
```
which in turn is TFLite's [tflite::evaluation::ImagePreprocessingStage::AddDefaultNormalizationStep()]( https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/evaluation/stages/image_preprocessing_stage.h#L162-L176). As you can see,
```C++
void AddDefaultNormalizationStep() {
    switch (
        config_.specification().image_preprocessing_params().output_type()) {
      case kTfLiteFloat32:
        AddNormalizationStep(127.5, 1.0 / 127.5);
        break;
      case kTfLiteUInt8:
        break;
      case kTfLiteInt8:
        AddNormalizationStep(128.0, 1.0);
        break;
      default:
        LOG(ERROR) << "Type not supported";
        break;
    }
}
```

And you can find what 

> 2. Where I can find the label for imageNet dataset? I can't reproduce the same accuracy result even with the tflite backend for mobilenet_edge_tpu. Can anyone upload the imagenet_val_full.txt for groundtruth file?

It's distributed with ImageNet. I guess we cannot distribute it due to license issue.

> 3. For every task in the benchmark, should vendor only provide one model for each task for submission?

What do you mean by "one model for each task"? For closed one, yes, say, if you have both float and quantized models, you have to choose one to submit. For open one, you are free to submit as many models as you want.

Please check submission docs below,
1. https://github.com/mlcommons/mobile_open/blob/main/rules/submissionRuleV2_0.adoc
2. https://github.com/mlcommons/mobile_open/blob/main/rules/mobile_inference_rules.adoc

And maybe you or your colleagues want to join [mobile working group's weekly meeting](https://mlcommons.org/en/groups/inference-mobile/)

**Comment by freedomtan** [comment]
@TheKanter You might be interested knowing this that Rockchip is interested in adding a new backend.

**Comment by TheKanter** [comment]
Hi @NullCarrier can you contact me via email? david@mlcommons.org ?

**Comment by NullCarrier** [comment]
HI, @freedomtan , thanks very much for the reply, we are making progress on implementing backend for RK3588. And @TheKanter , I am gonna close this issue and contact you later on via the email, thanks for the help
