### ISSUE TITLE
Capability to run the flutter app from command line, without connecting to internet

### ISSUE THREAD

**Issue by mohitmundhragithub** [mlcommons/mobile_app_open#424]
The previous android app, we had the capability to run directly from the command line without connecting to internet. The steps to do this was,

1) Have all local paths for all the models in backend settings.
2) Have local paths for all the datasets in a tasks_v4.pbtxt file and push the file to /sdcard/mlperf_datasets.

Once we have above things, the app will pick up /sdcard/mlperf_datasets/tasks_v4.pbtxt instead of downloading the config file from github.
In the flutter based app, we were able to figure out a way to have local path for models in backend settings. But, wanted to know if there is a way to make the app not download the tasks file?

Moreover, we could use below set of commands to run the app from command line using adb. Any way to run the flutter app using command line?

#run the app via adb
adb shell pm grant org.mlperf.inference android.permission.WRITE_EXTERNAL_STORAGE
adb shell pm grant org.mlperf.inference android.permission.READ_PHONE_STATE
adb shell pm grant org.mlperf.inference android.permission.READ_EXTERNAL_STORAGE
adb shell "am start -n org.mlperf.inference/.activities.CalculatingActivity --ez 'AUTO_START' true"

**Comment by d-uzlov** [comment]
We have recently moved the default task config into this repo so app no longer downloads it in the last commit.

I believe you should also be able to avoid downloading datasets from the default task config if you copy all the files app tries to download into the app folder with corresponding paths prior to running it.

We do have the [autostart script for the app](https://github.com/mlcommons/mobile_app_open/blob/b8682c9a5ad872209a4e19181ea144e1e60afc55/flutter/autostart-run.sh) but it requires flutter with corresponding platform SDK to be installed on the host machine because it recompiles the app to make it run automatically.
