### ISSUE TITLE
Change mlperf_datasets directory to /sdcard to accommodate flutter for older devices 

### ISSUE THREAD

**Issue by AhmedTElthakeb** [mlcommons/mobile_app_open#511]
For older devices with Android 11, an issue is observed with accessing mlperf_datasets directory required by flutter app for submission mode runs. 

`E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Exists failed, path = '/storage/emulated/0/Android/data/org.mlcommons.android.mlperfbench/files/mlperf_datasets/imagenet/img' (OS Error: Permission denied, errno = 13)
    #0      _Directory.exists.<anonymous closure> (dart:io/directory_impl.dart:85)`

As such, we may need to change mlperf_datasets directory to /sdcard instead to accommodate flutter app for older devices.

**Comment by d-uzlov** [comment]
Could this be just an issue with your device?

Our CI for tflite backend uses Pixel 5 with Android SDK 30, which corresponds to Android 11, and we never saw any issues with access to the data folder.
Also I have run the same CI with SM-G981U1 (Samsung S20) with SDK 29 (Android 10) several times, and there were no issues.

If I remember correctly, using the `Android/data/<package-id>` was the preferred way to store data from about forever ago. I would think there should be no issues even as far back as on Android 4.

**Comment by AhmedTElthakeb** [comment]
Will try on other devices, but just to clarify I mean here the "full" dataset that is required for accuracy evaluation, performance mode runs with no problem. 

https://github.com/mlcommons/mobile_app_open/blob/83a93543dffff7d59249af55472e0bb67a42a260/flutter/assets/tasks.pbtxt#L16

**Comment by freedomtan** [comment]
@AhmedTElthakeb will verify this again. @freedomtan can try to find an Android 11 device.

**Comment by mohitmundhragithub** [comment]
>> E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)]

The error points to this file... But i don't see this file in the code base. Is this some local change?

**Comment by d-uzlov** [comment]
I believe it's a file from the Flutter framework.
Look at the full stack trace to find the place where the exception actually occurred.

**Comment by Mostelk** [comment]
Another issue, is copying the full accuracy datasets take time, and having  folder inside the App directory make it deleted every time you uninstall the App.

**Comment by freedomtan** [comment]
I tested some non-rooted Android 11 devices (including a Pixel 2 and some MTK devices) with vanilla TFLite backend, they all worked fine. So, I guess that's some kind of file/directory permission issues.

**Comment by freedomtan** [comment]
> Another issue, is copying the full accuracy datasets take time, and having folder inside the App directory make it deleted every time you uninstall the App.

That's a good point. Though, I don't think we have to uninstall frequently. @d-uzlov can we avoid the problem mentioned by @Mostelk.

**Comment by d-uzlov** [comment]
I guess the only solution to save the data when you uninstall the app is to keep the data outside of the application folder.

For example, we can make data folder configurable. By default it would be the app folder but there would be a button to choose a custom folder which won't be automatically deleted.

**Comment by AhmedTElthakeb** [comment]
[APK build by Ahn](https://drive.google.com/file/d/1wRZWMlaeBxDkp1yvUr2elj1A-kPCjGvZ/view) also did not work on S21+ for submission mode, but performance mode runs okay. 

adb push mlperf_datasets is not permitted under the app directory. Only internal copying is allowed from /sdcard to the app directory; yet, the app, during submission mode, cannot access mlperf_datasets, only performance mode runs.

**Comment by freedomtan** [comment]
For android devices, the `/sdcard/Download/` is supposed to be shared across all apps. Let's see if we can use this folder. We can make it possible for users to choose where the `mlpert_datasets/` is located.

@anhappdev & @d-uzlov

**Comment by anhappdev** [comment]
Maybe we can use this package:
https://pub.dev/packages/file_picker

**Comment by Mostelk** [comment]
> Maybe we can use this package: https://pub.dev/packages/file_picker

Does it allow us to pick the user-loaded mlperf_datasets directory, or only pick a single file? We can still keep default setting for the downloaded datasets, or this will be a directory for all datasets?

**Comment by anhappdev** [comment]
> Does it allow us to pick the user-loaded mlperf_datasets directory, or only pick a single file?

It's possible to pick a directory.

> We can still keep default setting for the downloaded datasets, or this will be a directory for all datasets?

Not sure yet, but theoretically the user can choose one directory and the app downloads all files to that directory. It has the benefit that uninstalling the app doesn't delete downloaded files. Actually, I think that is a good idea to let the user choose one directory as a `app:\\` directory. All data (images, models, log, etc.) will be stored there. So `app:\\` would translate to a user-defined directory instead of fixed application directory like now. So this approach would work for all platforms.

**Comment by freedomtan** [comment]
I think it should be a directory. For example, currently, we are put `mlperf_datasets/` into `/sdcard/Android/data/org.mlcommons.android.mlperfbench/files`. If we choose `/sdcard/Download/foobar/`, then `mlperf_datasets` is supposed to be in `/sdcard/Download/foobar/`.

Choosing "root" of `app://` on sounds good. But removing an app without touching its `app://` directory doesn't always sound right to me.

**Comment by Mostelk** [comment]
Yes agreed it should be a directory and it can have both the downloaded data, and the user moved data (accuracy dataset). This will be useful for CI as well, to have a pre-specified directory, you don't need to download the new data every-time, as for testing environment sometimes there is no internet, and CI can be used to test submission mode as well, if the accuracy dataset has already been put in a prespecified directory (we can pick a default directory like /Download).

**Comment by d-uzlov** [comment]
I think that there should be at least 2 data folders:
1. For online cache
2. For data that is managed manually

Both should be configurable separately.

Few thoughts about cache folder:
* Most of the time users don't need to touch downloaded files.
  * As Freedom pointed out, it would be weird if the cache would remain in the device storage after you deleted the app
  * In Android there is an option to use a special cache folder that can be cleared automatically or manually separately from other app data.
  * On iOS we can probably also move cache to a separate folder that is not accessible from the `Files` app
* But we will still have the option to move download cache to somewhere else
  * On our Firebase CI there is no use for it, but it can benefit vendors
  * We can make it configurable via build options, so you don't have to change it manually after each app reinstall

Few thoughts about data folder:
* By default we can still point it to the app directory
  * Same as with cache folder, Android users will be able to use system tools to delete files if they need to
  * We can make it configurable via build options, so you don't have to change it manually after each app reinstall
* We can use `data://` prefix in the tasks config file instead of the `app://` to make it less confusing

I also think we should have a separate option for the logs folder.
Same as data folder, it should be in the app folder by default but can be changed to make it easier to access.

**Comment by AhmedTElthakeb** [comment]
Is there any update on this?

**Comment by d-uzlov** [comment]
I haven't started working on it yet.
I can take it after I finish my current pull request.

**Comment by freedomtan** [comment]
Let's prioritize this

**Comment by anhappdev** [comment]
Let agree upon how we want to implement it first.
I would summarize above discussions and translate it to the following implementation approach:
1. Paths with `https://` prefix will be downloaded into the application directory like before.
2. Paths with `app://` prefix with be translated to a custom directory. This custom directory defaults to application directory (like until now) but can be changed in the settings screen.

This approach will not cause many changes in the code and quick to implement.

**Comment by d-uzlov** [comment]
> * Paths with `https://` prefix will be downloaded into the application directory like before.
> * Paths with `app://` prefix with be translated to a custom directory. This custom directory defaults to application directory (like until now) but can be changed in the settings screen.

I agree, except I think both directories should be configurable.

**Comment by anhappdev** [comment]
> I agree, except I think both directories should be configurable.

The app will download `https://` links on start so if it's configurable, the user should be able to set it on the first app start, which will make the flow (and code changes) more complex. If there is no important use case for it now, I prefer not to do it. We can always add it later if we really need it.
BTW, if a vendor wants to avoid download `https://` links, a custom task file with all local paths would be more appropriate.

**Comment by d-uzlov** [comment]
> the user should be able to set it on the first app start

Makes sense.
We can omit the UI option for `https` cache folder but still keep the ability to set a custom one it during build.

**Comment by anhappdev** [comment]
> Makes sense. We can omit the UI option for `https` cache folder but still keep the ability to set a custom one during build.

I think the ability to add and set a custom task file as default during build is more appropriate. We can also add a new one with local paths only for convenience.

Adding the build option to set a default location for storing `https` files means each build can have a different location, we will then probably need a UI to show the custom location to know where the file is stored. Another issue would be that the custom location is likely a fixed string, which may work on Android, but not on iOS since iOS is heavily sandboxed. The file picker will work because it can get the path dynamically and request permission from the OS to access to the path, but a fixed string most likely not.

**Comment by d-uzlov** [comment]
> we will then probably need a UI to show the custom location to know where the file is stored

Yeah, we probably should.

> which may work on Android, but not on iOS since iOS is heavily sandboxed

Obviously custom folders are platform dependent.
If I remember correctly, this was the primary reason we switched to app folder for all data in the first place, because iOS and Windows don't really have an /sdcard folder.

> but a fixed string most likely not

My intent is to use it for test builds.
So you create a certain build with some backend and set a custom folder for your certain device that you are using.
This build may not work on any other device, and that's okay.

_Release builds should always use the default settings._

> I think the ability to add and set a custom task file as default during build is more appropriate. We can also add a new one with local paths only for convenience.

Task config with local paths is a kinda different use case.

---

### Use case 1 for custom http cache folder

1. You install the app 
2. App downloads required files
3. You delete the app and install a different build
4. App can reuse existing cache

This use case requires using custom cache folder.

Not applicable to end users.

---

### Use case 2 for custom http cache folder

1. You put pre-cached data to device
2. App can work without internet access

This use case technically can be solved using a separate task config.
But I would prefer to use some other device with the internet access to download files and then copy the whole cache folder to the device without internet. This way you don't need to download anything manually.

Not applicable to end users.

---

### Use case 1 for custom data folder

1. You use `adb` to push accuracy mode files into a certain folder
2. You create a build that would use that folder
3. You can run [fully or partially] automated tests

Not applicable to end users.

---

### Use case 2 for custom data folder

1. You open the app
2. You go to app settings
3. You use file picker to select some folder on your device which contains required files

The only case that is applicable to end users.

---

### Use case for a custom task config file

1. You download or create files manually
2. You put files into some file tree.
3. You create a custom config that matches your file tree.

If you want to use a predefined task config, you have to create the file tree that matches the one used in the config. At which point you may as well use the default config.

---

Please, correct me if I miss anything.

**Comment by d-uzlov** [comment]
> This use case technically can be solved using a separate task config.
> But I would prefer to use some other device with the internet access to download files and then copy the whole cache folder to the device without internet. This way you don't need to download anything manually.

Also custom task config don't affect backend settings.

**Comment by anhappdev** [comment]
Most of the use cases are special cases for vendors and CI, right?

What if we add a `build option` to configure the default application directory (where downloaded files and app generated files are stored)? No need for customizing the `app:\\` prefix anymore. This solution would be more simple.

**Comment by d-uzlov** [comment]
> Most of the use cases are special cases for vendors and CI, right?

Yep.

> What if we add a `build option` to configure the default application directory (where downloaded files and app generated files are stored)? No need for customizing the `app:\\` prefix anymore. This solution would be more simple.

This is what I'm going to do with the cache folder.
But there is still a case for end users for the accuracy testing.

**Comment by anhappdev** [comment]
Normal end users will most likely do not have the dataset required for accuracy testing.

Anyway, I think it's ok to do both as you suggest:
1. Add a build option to configure the default application directory
2. User can change the default location for the `app:\\` prefix in the app settings

**Comment by d-uzlov** [comment]
> Normal end users will most likely do not have the dataset required for accuracy testing

Well, here I mean just users that don't build the app themselves :)

**Comment by anhappdev** [comment]
Great. Let do it. The discussion is a bit long but it takes certainly less time to think it through first than code it and change it later in the PR review.
