### ISSUE TITLE
Avoid manually handling of JSON serialization

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#518]
We have many classes with `manual` JSON serialization and will have more.
https://github.com/mlcommons/mobile_app_open/search?q=fromJson
https://github.com/mlcommons/mobile_app_open/search?q=toJson

Since we already use [Protocol Buffers](https://developers.google.com/protocol-buffers) in the app (e.g. [mlperf_task.proto](https://github.com/mlcommons/mobile_app_open/blob/master/flutter/cpp/proto/mlperf_task.proto)), maybe we can also switch to use Protocol Buffers. The benefits are described here: [What are the Benefits of Using Protocol Buffers?](https://developers.google.com/protocol-buffers/docs/overview#benefits)

**Comment by d-uzlov** [comment]
Most of the serialization are for exporting the data to firebase via a Node server (== typescript/javascript code).
* I don't see neither typescript nor javascript listed as a an officially supported language
* Firebase internally works with JSON. Even if we somehow make protobuf work with TS/JS, we would get additional conversions `protobuf → json` and `json → protobuf` with possible bugs and unwanted side-effects.

Also, Dart can't work with the text form of protobuf. We use a special native function in the backend bridge because of it:
https://github.com/mlcommons/mobile_app_open/blob/264e8c13587612a34fee3090c5a3ac884c6870bd/flutter/cpp/flutter/dart_mlperf_config.cc#L13-L15
Not sure how often we will really need the text form of data but it's very convenient for logging and debugging.

Maybe it would be convenient to have declarations of data classes in a separate file, without some language specific stuff (or maybe it wouldn't be). But I think it doesn't justify potential compatibility issues with protobuf either way.

**Comment by d-uzlov** [comment]
I do agree that we have uncomfortably large amount of JSON serialization code in the repo.
I think it could solved by using code generation.
Particularly there is this library: https://pub.dev/packages/json_serializable

**Comment by d-uzlov** [comment]
> Since we already use [Protocol Buffers](https://developers.google.com/protocol-buffers) in the app (e.g. [mlperf_task.proto](https://github.com/mlcommons/mobile_app_open/blob/master/flutter/cpp/proto/mlperf_task.proto)

By the way, if anything, I would like to switch from protobuf to YAML for that particular file. Protobuf is not built for configuration files.
I don't see a point spending time on this, though, since it's just one file which we rarely edit.

**Comment by anhappdev** [comment]
`json_serializable` would also work. Let update the title to focus on the main issue which is manually handling of JSON serialization.

**Comment by anhappdev** [comment]
Currently, if the `tag` (JSON key) is changed, the JSON file will be failed to parse.
If the `tag` does not match, the JSON file should still be parsed, but the unmatched tag will be empty. This should be the default behavior instead of dropping the old results and create a new JSON file.
Let also implement that this in this issue.

**Comment by d-uzlov** [comment]
@anhappdev have you started working on this?
If not I'll take it.

**Comment by anhappdev** [comment]
@d-uzlov You can take it. Thanks.
