### ISSUE TITLE
Mobile_app PR 591 - is this needed in mobile_app_open

### ISSUE THREAD

**Issue by relja128** [mlcommons/mobile_app_open#54]
If so, can you please open an issue in this repo that explains what we're fixing?
https://github.com/mlcommons/mobile_app/pull/591

**Comment by mohitmundhragithub** [comment]
Currently all the datasets other than imagenet works fine, if we don't have the ground truth files. However, for imagenet, not having the groudtruth file crashes the app. 

As long as we run the app with internet connected, its not a problem, because the app downloads ground truth file for imagenet. But when running without internet, by pushing all the dataset other than ground truth file, it hits this assert. The PR changes the log from "FATAL" to "ERROR" to remove this dependency. 

Its good to have thing for anyone who wants to run the app without internet.
