### ISSUE TITLE
Add a test that backend doesn't use accelerator fallbacks

### ISSUE THREAD

**Issue by d-uzlov** [mlcommons/mobile_app_open#590]
Some backends (particularly, TFLite backend and those which are based on it) can use accelerator fallback.
If accelerator code in config is invalid, or if current device just doesn't have the specified accelerator, backend will use CPU instead, to make sure the app at least works, even if the performance is low.

We should add a check into our integration test that backend doesn't do it, to make sure backend config is correct.

**Comment by anhappdev** [comment]
I think there is no need for this kind of test right now because:
1. We already have a throughput test. If a device does not use the accelerator as expected, the throughput will drop and fail the test.
2. All backends must correctly report the accelerator used but it's not required for now and only some backends do it, but as a string with no unified format, which make the checks difficult. See https://github.com/mlcommons/mobile_app_open/pull/576#discussion_r1004310185 for more detail.

Therefore, I will close this issue for now. @freedomtan Please reopen this if you think we should do it.
