### ISSUE TITLE
v3.0-windows to support Intel platforms

### ISSUE THREAD

**Issue by andyyeh75** [mlcommons/mobile_app_open#778]
Per this release tag,

[https://github.com/mlcommons/mobile_app_open/releases/tag/v3.0-windows](https://github.com/mlcommons/mobile_app_open/releases/tag/v3.0-windows)

Could someone help build the v3.0-windows to support Intel platforms. Just like v2.0 which had Intel in the support list. Thanks a lot for your great help.

**Comment by freedomtan** [comment]
> Per this release tag,
> 
> https://github.com/mlcommons/mobile_app_open/releases/tag/v3.0-windows
> 
> Could someone help build the v3.0-windows to support Intel platforms. Just like v2.0 which had Intel in the support list. Thanks a lot for your great help.

Hi Andy,

For on windows, what we have are
- TFLite backend for the Flutter app
-  SNPE backend for the [command line program](https://github.com/mlcommons/mobile_app_open/tree/master/flutter/cpp/binary)

For 2.0 and older submissions, some Intel colleguages used the code from the [main inference repo](https://github.com/mlcommons/inference) to submit OpenVINO-based results.

If you are interested in adding OpenVINO backend to the app, you are more than welcome to join our weekly engineering meeting (Tue 1-2 pm or 2-3 pm Taiwan time, because it's actually Mon 22:00 pacific time) and the [Mobile Google Group](https://groups.google.com/a/mlcommons.org/g/mobile) meeting.
 
@mohitmundhragithub and @anhappdev correct me if I am wrong.

**Comment by mohitmundhragithub** [comment]
> > Per this release tag,
> > 
> > https://github.com/mlcommons/mobile_app_open/releases/tag/v3.0-windows
> > 
> > Could someone help build the v3.0-windows to support Intel platforms. Just like v2.0 which had Intel in the support list. Thanks a lot for your great help.
> 
> Hi Andy,
> 
> For on windows, what we have are
> - TFLite backend for the Flutter app
> -  SNPE backend for the [command line program](https://github.com/mlcommons/mobile_app_open/tree/master/flutter/cpp/binary)
> 
> For 2.0 and older submissions, some Intel colleguages used the code from the [main inference repo](https://github.com/mlcommons/inference) to submit OpenVINO-based results.
> 
> If you are interested in adding OpenVINO backend to the app, you are more than welcome to join our weekly engineering meeting (Tue 1-2 pm or 2-3 pm Taiwan time, because it's actually Mon 22:00 pacific time) and the [Mobile Google Group](https://groups.google.com/a/mlcommons.org/g/mobile) meeting.
>  
> @mohitmundhragithub and @anhappdev correct me if I am wrong.

Yes. You are right. Openvino support was not added to the app yet.

**Comment by freedomtan** [comment]
@andyyeh75 if you can talk to @attafosu, who is an Intel representative to MLCommons, too

**Comment by andyyeh75** [comment]
Thank a lot to answer my query. Closed the bug for further following up.
