### ISSUE TITLE
Cannot pass parameters/config files using am start command

### ISSUE THREAD

**Issue by IshanG97** [mlcommons/mobile_app_open#784]
Since not all infrastructure setups use Firebase Test Lab and flutter integration testing, there must be way to pass custom parameters via CLI. One approach that worked in MLPerf v0.7.1 (and maybe versions of the app upto the point it was ported to flutter) was using the 'am start' command. Some of the parameters of interest;
1. models - this can be adjust by adding the custom tasks.pbtxt location in benchmarksConfigurations.json
2. accelerator (nnapi, gpu)
3. run_mode (performance, accuracy, submission)
4. internet_connection (Offline Mode)
5. cooldown_between_workloads (enabled, disabled)
6. cooldown_interval_in_minutes: (1, 2, etc)
7. number of threads (1, 2, 4, etc)

**Comment by freedomtan** [comment]
- it seems to be possible to wrap around flutter to support some kind of extra controls, but perhaps not for android `am start ....` 
```
flutter run .......
```
should be able to provide some of the functions mentioned by @IshanG97.

We have to add some code so that we can use `flutter run ...`.

We cannot have them all too fast, have to do add them one by one.

@IshanG97: is this acceptable? or you really need `am start ...`? if that's acceptable, what's priority for the seven items?

**Comment by freedomtan** [comment]
@IshanG97 I assume you don't have further problems. Close this for now.

**Comment by IshanG97** [comment]
Hi, is there a way to launch this using a command like this?
`adb shell am start -n com.package.name/io.flutter.embedding.android.FlutterActivity`

I saw some references here: https://docs.flutter.dev/cookbook/navigation/set-up-app-links
and here (search for "flutter" on the page, the comment is at the bottom): https://stackoverflow.com/questions/4567904/how-to-start-an-application-using-android-adb-tools
