### ISSUE TITLE
Add CI support for building the app from mobile_app_open

### ISSUE THREAD

**Issue by mcharleb** [mlcommons/mobile_app_open#8]

**Comment by bellycat77** [comment]
@relja128 @mcharleb
Jenkins jobs were configured:
1. Merging to the **master** branch
https://mlperf.xored.com/job/mobile_app_open/job/MasterBuild/
Starts automatically, because the **master** branch is protected so only approved/tested pull request can be merged.

2. Pull requests building:
https://mlperf.xored.com/job/mobile_app_open/job/PullRequest-Build/
After creating PR it will be built only in case the author is in the whitelisted organization **mlcommons**
In case the author of PR is not in **mlcommons**, then PR will not be built/tested. In that case, someone from **mlcommons** should add the comment `ok to test` to PR, then the Jenkins server will run building/testing.
